CREATE TABLE IF NOT EXISTS public.industries (
    id SERIAL PRIMARY KEY,
    industry_name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.sectors (
    id SERIAL PRIMARY KEY,
    sector_name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.tickers (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(16) NOT NULL UNIQUE,
    security_name VARCHAR(255) NOT NULL,
    industry_id INT,
    sector_id INT,
    day_high NUMERIC,
    day_low NUMERIC,
    fifty_day_average NUMERIC,
    last_price NUMERIC,
    last_volume NUMERIC,
    market_cap NUMERIC,
    open NUMERIC,
    previous_close NUMERIC,
    regular_market_previous_close NUMERIC,
    year_high NUMERIC,
    year_low NUMERIC,
    shares NUMERIC,
    ten_day_average_volume NUMERIC,
    three_month_average_volume NUMERIC,
    two_hundred_day_average NUMERIC,
    yearChange NUMERIC,
    CONSTRAINT fk_industry FOREIGN KEY (industry_id) REFERENCES industries (id) ON DELETE SET NULL,
    CONSTRAINT fk_sector FOREIGN KEY (sector_id) REFERENCES sectors (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.company (
    id SERIAL PRIMARY KEY,
    ticker_id INT REFERENCES tickers(id) ON DELETE CASCADE,
    short_name VARCHAR(255),
    long_name VARCHAR(255),
    industry VARCHAR(255),
    industry_key VARCHAR(255),
    industry_disp VARCHAR(255),
    sector VARCHAR(255),
    sector_key VARCHAR(255),
    sector_disp VARCHAR(255),
    address1 TEXT,
    address2 TEXT,
    city VARCHAR(255),
    zip VARCHAR(20),
    country VARCHAR(100),
    phone VARCHAR(50),
    fax VARCHAR(50),
    website VARCHAR(255),
    long_business_summary TEXT,
    full_time_employees INT,
    currency VARCHAR(10),
    exchange VARCHAR(50),
    quote_type VARCHAR(50),
    symbol VARCHAR(50),
    underlying_symbol VARCHAR(50),
    CONSTRAINT fk_ticker FOREIGN KEY (ticker_id) REFERENCES tickers (id) ON DELETE SET NULL,
    CONSTRAINT unique_ticker_id UNIQUE (ticker_id)
);

CREATE TABLE IF NOT EXISTS public.company_officers (
    id SERIAL PRIMARY KEY,
    ticker_id INT REFERENCES tickers(id) ON DELETE CASCADE,
    name VARCHAR(255),
    age INT,
    title VARCHAR(255),
    year_born INT,
    fiscal_year INT,
    total_pay NUMERIC,
    exercised_value NUMERIC,
    unexercised_value NUMERIC,
    CONSTRAINT fk_ticker FOREIGN KEY (ticker_id) REFERENCES tickers (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.risk_metrics (
    id SERIAL PRIMARY KEY,
    ticker_id INT REFERENCES tickers(id) ON DELETE CASCADE,
    audit_risk INT,
    board_risk INT,
    compensation_risk INT,
    shareholder_rights_risk INT,
    overall_risk INT,
    governance_epoch_date BIGINT,
    compensation_as_of_epoch_date BIGINT,
    CONSTRAINT fk_ticker FOREIGN KEY (ticker_id) REFERENCES tickers (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.financial_metrics (
    id SERIAL PRIMARY KEY,
    ticker_id INT REFERENCES tickers(id) ON DELETE CASCADE,
    price_hint INT,
    previous_close NUMERIC,
    open_price NUMERIC,
    day_low NUMERIC,
    day_high NUMERIC,
    regular_market_previous_close NUMERIC,
    regular_market_open NUMERIC,
    regular_market_day_low NUMERIC,
    regular_market_day_high NUMERIC,
    dividend_rate NUMERIC,
    dividend_yield NUMERIC,
    ex_dividend_date BIGINT,
    payout_ratio NUMERIC,
    five_year_avg_dividend_yield NUMERIC,
    beta NUMERIC,
    trailing_pe NUMERIC,
    forward_pe NUMERIC,
    volume BIGINT,
    regular_market_volume BIGINT,
    average_volume BIGINT,
    average_volume_10days BIGINT,
    ask NUMERIC,
    market_cap BIGINT,
    fifty_two_week_low NUMERIC,
    fifty_two_week_high NUMERIC,
    price_to_sales_trailing_12_months NUMERIC,
    fifty_day_average NUMERIC,
    two_hundred_day_average NUMERIC,
    trailing_annual_dividend_rate NUMERIC,
    trailing_annual_dividend_yield NUMERIC,
    enterprise_value BIGINT,
    profit_margins NUMERIC,
    float_shares BIGINT,
    shares_outstanding BIGINT,
    held_percent_insiders NUMERIC,
    held_percent_institutions NUMERIC,
    implied_shares_outstanding BIGINT,
    book_value NUMERIC,
    price_to_book NUMERIC,
    last_fiscal_year_end BIGINT,
    next_fiscal_year_end BIGINT,
    most_recent_quarter BIGINT,
    earnings_quarterly_growth NUMERIC,
    net_income_to_common BIGINT,
    trailing_eps NUMERIC,
    forward_eps NUMERIC,
    last_split_factor VARCHAR(10),
    last_split_date BIGINT,
    enterprise_to_revenue NUMERIC,
    enterprise_to_ebitda NUMERIC,
    CONSTRAINT fk_ticker FOREIGN KEY (ticker_id) REFERENCES tickers (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.analyst_ratings (
    id SERIAL PRIMARY KEY,
    ticker_id INT REFERENCES tickers(id) ON DELETE CASCADE,
    target_high_price NUMERIC,
    target_low_price NUMERIC,
    target_mean_price NUMERIC,
    target_median_price NUMERIC,
    recommendation_mean NUMERIC,
    recommendation_key VARCHAR(50),
    number_of_analyst_opinions INT,
    CONSTRAINT fk_ticker FOREIGN KEY (ticker_id) REFERENCES tickers (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.dividend_metrics (
    id SERIAL PRIMARY KEY,
    ticker_id INT REFERENCES tickers(id) ON DELETE CASCADE,
    last_dividend_value NUMERIC,
    last_dividend_date BIGINT,
    CONSTRAINT fk_ticker FOREIGN KEY (ticker_id) REFERENCES tickers (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.dividends (
    id SERIAL PRIMARY KEY,
    ticker_id INT REFERENCES tickers(id) ON DELETE CASCADE,
    price NUMERIC,
    action_date TIMESTAMP NOT NULL UNIQUE,
    CONSTRAINT fk_ticker FOREIGN KEY (ticker_id) REFERENCES tickers (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.stock_splits (
    id SERIAL PRIMARY KEY,
    ticker_id INT REFERENCES tickers(id) ON DELETE CASCADE,
    price NUMERIC,
    action_date TIMESTAMP NOT NULL UNIQUE,
    CONSTRAINT fk_ticker FOREIGN KEY (ticker_id) REFERENCES tickers (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.balance_sheets (
    id SERIAL PRIMARY KEY,
    ticker_id INT REFERENCES tickers(id) ON DELETE CASCADE,
    report_date TIMESTAMP NOT NULL,
    treasury_shares_number NUMERIC,
    ordinary_shares_number NUMERIC,
    share_issued NUMERIC,
    total_debt NUMERIC,
    tangible_book_value NUMERIC,
    invested_capital NUMERIC,
    working_capital NUMERIC,
    net_tangible_assets NUMERIC,
    capital_lease_obligations NUMERIC,
    common_stock_equity NUMERIC,
    total_capitalization NUMERIC,
    total_equity_gross_minority_interest NUMERIC,
    stockholders_equity NUMERIC,
    other_equity_interest NUMERIC,
    retained_earnings NUMERIC,
    additional_paid_in_capital NUMERIC,
    capital_stock NUMERIC,
    common_stock NUMERIC,
    total_liabilities_net_minority_interest NUMERIC,
    total_non_current_liabilities_net_minority_interest NUMERIC,
    derivative_product_liabilities NUMERIC,
    long_term_debt_and_capital_lease_obligation NUMERIC,
    long_term_capital_lease_obligation NUMERIC,
    long_term_debt NUMERIC,
    long_term_provisions NUMERIC,
    current_liabilities NUMERIC,
    other_current_liabilities NUMERIC,
    current_deferred_taxes_liabilities NUMERIC,
    current_debt_and_capital_lease_obligation NUMERIC,
    current_capital_lease_obligation NUMERIC,
    pension_and_other_post_retirement_benefit_plans_current NUMERIC,
    current_provisions NUMERIC,
    payables NUMERIC,
    other_payable NUMERIC,
    dividends_payable NUMERIC,
    total_tax_payable NUMERIC,
    accounts_payable NUMERIC,
    total_assets NUMERIC,
    total_non_current_assets NUMERIC,
    other_non_current_assets NUMERIC,
    non_current_prepaid_assets NUMERIC,
    non_current_deferred_taxes_assets NUMERIC,
    financial_assets NUMERIC,
    other_investments NUMERIC,
    investment_in_financial_assets NUMERIC,
    available_for_sale_securities NUMERIC,
    goodwill_and_other_intangible_assets NUMERIC,
    other_intangible_assets NUMERIC,
    goodwill NUMERIC,
    net_ppe NUMERIC,
    accumulated_depreciation NUMERIC,
    gross_ppe NUMERIC,
    construction_in_progress NUMERIC,
    other_properties NUMERIC,
    machinery_furniture_equipment NUMERIC,
    buildings_and_improvements NUMERIC,
    land_and_improvements NUMERIC,
    properties NUMERIC,
    current_assets NUMERIC,
    other_current_assets NUMERIC,
    hedging_assets_current NUMERIC,
    assets_held_for_sale_current NUMERIC,
    restricted_cash NUMERIC,
    prepaid_assets NUMERIC,
    inventory NUMERIC,
    finished_goods NUMERIC,
    work_in_process NUMERIC,
    raw_materials NUMERIC,
    other_receivables NUMERIC,
    taxes_receivable NUMERIC,
    accounts_receivable NUMERIC,
    allowance_for_doubtful_accounts_receivable NUMERIC,
    gross_accounts_receivable NUMERIC,
    cash_cash_equivalents_and_short_term_investments NUMERIC,
    other_short_term_investments NUMERIC,
    cash_and_cash_equivalents NUMERIC,
    cash_equivalents NUMERIC,
    cash_financial NUMERIC,
    CONSTRAINT fk_ticker FOREIGN KEY (ticker_id) REFERENCES tickers (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.cashflows (
    id SERIAL PRIMARY KEY,
    ticker_id INT REFERENCES tickers(id) ON DELETE CASCADE,
    report_date TIMESTAMP NOT NULL,
    free_cash_flow NUMERIC,
    capital_expenditure NUMERIC,
    end_cash_position NUMERIC,
    beginning_cash_position NUMERIC,
    effect_of_exchange_rate_changes NUMERIC,
    changes_in_cash NUMERIC,
    financing_cash_flow NUMERIC,
    interest_paid_cff NUMERIC,
    cash_dividends_paid NUMERIC,
    common_stock_dividend_paid NUMERIC,
    investing_cash_flow NUMERIC,
    net_other_investing_changes NUMERIC,
    interest_received_cfi NUMERIC,
    net_investment_purchase_and_sale NUMERIC,
    sale_of_investment NUMERIC,
    purchase_of_investment NUMERIC,
    net_business_purchase_and_sale NUMERIC,
    sale_of_business NUMERIC,
    purchase_of_business NUMERIC,
    net_ppe_purchase_and_sale NUMERIC,
    sale_of_ppe NUMERIC,
    purchase_of_ppe NUMERIC,
    operating_cash_flow NUMERIC,
    taxes_refund_paid NUMERIC,
    change_in_working_capital NUMERIC,
    change_in_other_current_liabilities NUMERIC,
    change_in_other_current_assets NUMERIC,
    change_in_payable NUMERIC,
    change_in_inventory NUMERIC,
    change_in_receivables NUMERIC,
    other_non_cash_items NUMERIC,
    provisionand_write_offof_assets NUMERIC,
    depreciation_and_amortization NUMERIC,
    amortization_cash_flow NUMERIC,
    depreciation NUMERIC,
    gain_loss_on_investment_securities NUMERIC,
    net_foreign_currency_exchange_gain_loss NUMERIC,
    gain_loss_on_sale_of_ppe NUMERIC,
    gain_loss_on_sale_of_business NUMERIC,
    net_income_from_continuing_operations NUMERIC,
    CONSTRAINT fk_ticker FOREIGN KEY (ticker_id) REFERENCES tickers (id) ON DELETE SET NULL
);